Mailer and rejector added but wont compile
PS C:\Users\Corma\Desktop\College\Courses\Semester 7\Distributed Systems\DS-Assignment-2> cdk destroy
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!                                                                            !!
!!  Node 19 has reached end-of-life on 2023-06-01 and is not supported.       !!
!!  Please upgrade to a supported node version as soon as possible.           !!
!!                                                                            !!
!!  This software is currently running on node v19.1.0.                       !!
!!  As of the current release of this software, supported node releases are:  !!
!!  - ^20.0.0 (Planned end-of-life: 2026-04-30)                               !!
!!  - ^18.0.0 (Planned end-of-life: 2025-04-30)                               !!
!!                                                                            !!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
C:\Users\Corma\Desktop\College\Courses\Semester 7\Distributed Systems\DS-Assignment-2\node_modules\constructs\src\construct.ts:447
      throw new Error(`There is already a Construct with name '${childName}' in ${typeName}${name.length > 0 ? ' [' + name + ']' : ''}`);
            ^
Error: There is already a Construct with name 'SqsEventSource:EDAStackimgcreatedqueue852C6AE9' in NodejsFunction [ProcessImageFn]
    at Node.addChild (C:\Users\Corma\Desktop\College\Courses\Semester 7\Distributed Systems\DS-Assignment-2\node_modules\constructs\src\construct.ts:447:13)
    at new Node (C:\Users\Corma\Desktop\College\Courses\Semester 7\Distributed Systems\DS-Assignment-2\node_modules\constructs\src\construct.ts:71:17)
    at new Construct (C:\Users\Corma\Desktop\College\Courses\Semester 7\Distributed Systems\DS-Assignment-2\node_modules\constructs\src\construct.ts:499:17)
    at new Resource (C:\Users\Corma\Desktop\College\Courses\Semester 7\Distributed Systems\DS-Assignment-2\node_modules\aws-cdk-lib\core\lib\resource.js:1:875)
    at new EventSourceMapping (C:\Users\Corma\Desktop\College\Courses\Semester 7\Distributed Systems\DS-Assignment-2\node_modules\aws-cdk-lib\aws-lambda\lib\event-source-mapping.js:1:2062)
    at NodejsFunction.addEventSourceMapping (C:\Users\Corma\Desktop\College\Courses\Semester 7\Distributed Systems\DS-Assignment-2\node_modules\aws-cdk-lib\aws-lambda\lib\function-base.js:2:1916)
    at SqsEventSource.bind (C:\Users\Corma\Desktop\College\Courses\Semester 7\Distributed Systems\DS-Assignment-2\node_modules\aws-cdk-lib\aws-lambda-event-sources\lib\sqs.js:1:1824)
    at NodejsFunction.addEventSource (C:\Users\Corma\Desktop\College\Courses\Semester 7\Distributed Systems\DS-Assignment-2\node_modules\aws-cdk-lib\aws-lambda\lib\function-base.js:2:3450)
    at new EDAAppStack (C:\Users\Corma\Desktop\College\Courses\Semester 7\Distributed Systems\DS-Assignment-2\lib\eda-app-stack.ts:247:20)
    at Object.<anonymous> (C:\Users\Corma\Desktop\College\Courses\Semester 7\Distributed Systems\DS-Assignment-2\bin\eda-app.ts:7:1)

Subprocess exited with error 1